# Project
version=4.4.0
group=net.cinchtail.cinchsmissingblocks
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Cinch's Missing Blocks
mod_author=Cinchtail
mod_id=cinchsmissingblocks
license=ARR
credits=Texture artists: Stallman, Popopi, Myheadmess; translators: kierohere, Piotrus983
description=Adds missing vanilla-style building blocks and universal configurable vertical slabs.
minecraft_version_range=[1.21.1, 1.21.2)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.116.12+1.21.1
fabric_loader_version=0.19.2
yarn_mappings=1.21.1+build.3

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
