# Project
version=5.0.0
group=net.cinchtail.cinchsmissingblocks
java_version=25

# Common
minecraft_version=26.2
mod_name=Cinch's Missing Blocks
mod_author=Cinchtail
mod_id=cinchsmissingblocks
mod_license=ARR
mod_credits=Texture artists: Stallman, Popopi, Myheadmess, SplendorSender; translators: kierohere, Piotrus983, Shandro
mod_description=Adds all the blocks missing from minecraft.
mod_homepage=https://www.curseforge.com/minecraft/mc-mods/cinchs-missing-blocks
mod_issues=https://github.com/cinchtail/Cinchs_Missing_Blocks/issues
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.159.0+26.2
fabric_loader_version=0.19.5

# NeoForge
neoforge_version=26.2.0.75
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false