# Project
version=4.4.0
group=net.cinchtail.cinchsmissingblocks
java_version=25

# Common
minecraft_version=26.2
mod_name=Cinch's Missing Blocks
mod_author=Cinchtail
mod_id=cinchsmissingblocks
license=ARR
credits=Texture artists: Stallman, Popopi, Myheadmess; translators: kierohere, Piotrus983
description=Adds missing vanilla-style building blocks and universal configurable vertical slabs.
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.154.0+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
