package net.cinchtail.cinchsmissingblocks.item;

import net.cinchtail.cinchsmissingblocks.CinchsMissingBlocks;
import net.cinchtail.cinchsmissingblocks.block.ModBlocks;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class ModCreativeModeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB,
            CinchsMissingBlocks.MOD_ID);

    public static final RegistryObject<CreativeModeTab> CINCHS_MISSING_BLOCKS = CREATIVE_MODE_TABS.register("cinchs_missing_blocks",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(ModBlocks.CALCITE_BRICKS.get()))
                    .title(Component.literal("Cinch's Missing Blocks"))
                    .displayItems((displayParameters, output) -> {

                        output.accept(ModBlocks.CALCITE_STAIRS.get());
                        output.accept(ModBlocks.CALCITE_SLAB.get());
                        output.accept(ModBlocks.CALCITE_WALL.get());
                        output.accept(ModBlocks.POLISHED_CALCITE.get());
                        output.accept(ModBlocks.POLISHED_CALCITE_STAIRS.get());
                        output.accept(ModBlocks.POLISHED_CALCITE_SLAB.get());
                        output.accept(ModBlocks.POLISHED_CALCITE_WALL.get());
                        output.accept(ModBlocks.CALCITE_BRICKS.get());
                        output.accept(ModBlocks.CALCITE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CALCITE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CALCITE_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_CALCITE_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_CALCITE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_CALCITE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_CALCITE_BRICK_WALL.get());
                        output.accept(ModBlocks.MOSSY_CALCITE_BRICKS.get());
                        output.accept(ModBlocks.MOSSY_CALCITE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MOSSY_CALCITE_BRICK_SLAB.get());
                        output.accept(ModBlocks.MOSSY_CALCITE_BRICK_WALL.get());
                        output.accept(ModBlocks.DRIPSTONE_STAIRS.get());
                        output.accept(ModBlocks.DRIPSTONE_SLAB.get());
                        output.accept(ModBlocks.DRIPSTONE_WALL.get());
                        output.accept(ModBlocks.POLISHED_DRIPSTONE.get());
                        output.accept(ModBlocks.POLISHED_DRIPSTONE_STAIRS.get());
                        output.accept(ModBlocks.POLISHED_DRIPSTONE_SLAB.get());
                        output.accept(ModBlocks.POLISHED_DRIPSTONE_WALL.get());
                        output.accept(ModBlocks.DRIPSTONE_BRICKS.get());
                        output.accept(ModBlocks.DRIPSTONE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.DRIPSTONE_BRICK_SLAB.get());
                        output.accept(ModBlocks.DRIPSTONE_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_DRIPSTONE_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_DRIPSTONE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_DRIPSTONE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_DRIPSTONE_BRICK_WALL.get());
                        output.accept(ModBlocks.MOSSY_DRIPSTONE_BRICKS.get());
                        output.accept(ModBlocks.MOSSY_DRIPSTONE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MOSSY_DRIPSTONE_BRICK_SLAB.get());
                        output.accept(ModBlocks.MOSSY_DRIPSTONE_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_TUFF_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_TUFF_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_TUFF_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_TUFF_BRICK_WALL.get());
                        output.accept(ModBlocks.MOSSY_TUFF_BRICKS.get());
                        output.accept(ModBlocks.MOSSY_TUFF_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MOSSY_TUFF_BRICK_SLAB.get());
                        output.accept(ModBlocks.MOSSY_TUFF_BRICK_WALL.get());
                        output.accept(ModBlocks.POLISHED_ANDESITE_WALL.get());
                        output.accept(ModBlocks.ANDESITE_BRICKS.get());
                        output.accept(ModBlocks.ANDESITE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.ANDESITE_BRICK_SLAB.get());
                        output.accept(ModBlocks.ANDESITE_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_ANDESITE_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_ANDESITE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_ANDESITE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_ANDESITE_BRICK_WALL.get());
                        output.accept(ModBlocks.MOSSY_ANDESITE_BRICKS.get());
                        output.accept(ModBlocks.MOSSY_ANDESITE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MOSSY_ANDESITE_BRICK_SLAB.get());
                        output.accept(ModBlocks.MOSSY_ANDESITE_BRICK_WALL.get());
                        output.accept(ModBlocks.POLISHED_GRANITE_WALL.get());
                        output.accept(ModBlocks.POLISHED_DIORITE_WALL.get());
                        output.accept(ModBlocks.QUARTZ_WALL.get());
                        output.accept(ModBlocks.SMOOTH_QUARTZ_WALL.get());
                        output.accept(ModBlocks.QUARTZ_BRICK_STAIRS.get());
                        output.accept(ModBlocks.QUARTZ_BRICK_SLAB.get());
                        output.accept(ModBlocks.QUARTZ_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_QUARTZ_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_QUARTZ_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_QUARTZ_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_QUARTZ_BRICK_WALL.get());
                        output.accept(ModBlocks.MOSSY_QUARTZ_BRICKS.get());
                        output.accept(ModBlocks.MOSSY_QUARTZ_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MOSSY_QUARTZ_BRICK_SLAB.get());
                        output.accept(ModBlocks.MOSSY_QUARTZ_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_BRICK_WALL.get());
                        output.accept(ModBlocks.MOSSY_BRICKS.get());
                        output.accept(ModBlocks.MOSSY_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MOSSY_BRICK_SLAB.get());
                        output.accept(ModBlocks.MOSSY_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_MUD_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_MUD_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_MUD_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_MUD_BRICK_WALL.get());
                        output.accept(ModBlocks.MOSSY_MUD_BRICKS.get());
                        output.accept(ModBlocks.MOSSY_MUD_BRICK_STAIRS.get());
                        output.accept(ModBlocks.MOSSY_MUD_BRICK_SLAB.get());
                        output.accept(ModBlocks.MOSSY_MUD_BRICK_WALL.get());
                        output.accept(ModBlocks.CHISELED_MUD_BRICKS.get());
                        output.accept(ModBlocks.END_STONE_STAIRS.get());
                        output.accept(ModBlocks.END_STONE_SLAB.get());
                        output.accept(ModBlocks.END_STONE_WALL.get());
                        output.accept(ModBlocks.CRACKED_END_STONE_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_END_STONE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_END_STONE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_END_STONE_BRICK_WALL.get());
                        output.accept(ModBlocks.CHISELED_END_STONE_BRICKS.get());
                        output.accept(ModBlocks.STONE_WALL.get());
                        output.accept(ModBlocks.SMOOTH_STONE_STAIRS.get());
                        output.accept(ModBlocks.SMOOTH_STONE_WALL.get());
                        output.accept(ModBlocks.CRACKED_STONE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_STONE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_STONE_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_DEEPSLATE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_DEEPSLATE_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_DEEPSLATE_TILE_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_DEEPSLATE_TILE_SLAB.get());
                        output.accept(ModBlocks.CRACKED_DEEPSLATE_TILE_WALL.get());
                        output.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_NETHER_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_NETHER_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_NETHER_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_NETHER_BRICK_FENCE.get());
                        output.accept(ModBlocks.RED_NETHER_BRICK_FENCE.get());
                        output.accept(ModBlocks.CRACKED_RED_NETHER_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_RED_NETHER_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_RED_NETHER_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_RED_NETHER_BRICK_WALL.get());
                        output.accept(ModBlocks.CRACKED_RED_NETHER_BRICK_FENCE.get());
                        output.accept(ModBlocks.CHISELED_RED_NETHER_BRICKS.get());
                        output.accept(ModBlocks.PRISMARINE_BRICK_WALL.get());
                        output.accept(ModBlocks.DARK_PRISMARINE_WALL.get());
                        output.accept(ModBlocks.CRACKED_PRISMARINE_BRICKS.get());
                        output.accept(ModBlocks.CRACKED_PRISMARINE_BRICK_STAIRS.get());
                        output.accept(ModBlocks.CRACKED_PRISMARINE_BRICK_SLAB.get());
                        output.accept(ModBlocks.CRACKED_PRISMARINE_BRICK_WALL.get());
                        output.accept(ModBlocks.SMOOTH_BASALT_STAIRS.get());
                        output.accept(ModBlocks.SMOOTH_BASALT_SLAB.get());
                        output.accept(ModBlocks.SMOOTH_BASALT_WALL.get());
                        output.accept(ModBlocks.SMOOTH_SANDSTONE_WALL.get());
                        output.accept(ModBlocks.CUT_SANDSTONE_STAIRS.get());
                        output.accept(ModBlocks.CUT_SANDSTONE_WALL.get());
                        output.accept(ModBlocks.SMOOTH_RED_SANDSTONE_WALL.get());
                        output.accept(ModBlocks.CUT_RED_SANDSTONE_STAIRS.get());
                        output.accept(ModBlocks.CUT_RED_SANDSTONE_WALL.get());
                        output.accept(ModBlocks.PURPUR_WALL.get());
                    }).build());

    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
