package net.cinchtail.cinchsmissingblocks.item;

import net.cinchtail.cinchsmissingblocks.CinchsMissingBlocks;
import net.cinchtail.cinchsmissingblocks.block.ModBlocks;
import net.cinchtail.cinchsmissingblocks.config.ModConfigs;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashSet;
import java.util.Set;

import static net.cinchtail.cinchsmissingblocks.CinchsMissingBlocks.MOD_ID;

public class ModItemGroups {

    private static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);
    
    public static DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CinchsMissingBlocks.MOD_ID);

    public static String CINCHSMISSINGBLOCKS_TAB_TITLE = "itemgroup.cinchsmissingblocks";

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> CINCHSMISSINGBLOCKS_TAB = CREATIVE_MODE_TABS.register("cinchsmissingblocks_tab", () -> {
        CreativeModeTab.Builder builder = CreativeModeTab.builder();

        builder.displayItems((itemDisplay, output) -> {
            Set<Item> addedItems = new HashSet<>();

            for (DeferredHolder<Item, ? extends  Item> item : ModItems.ITEMS.getEntries())
                output.accept(ModBlocks.CALCITE_STAIRS);
            output.accept(ModBlocks.CALCITE_SLAB);
            output.accept(ModBlocks.CALCITE_WALL);
            output.accept(ModBlocks.POLISHED_CALCITE);
            output.accept(ModBlocks.POLISHED_CALCITE_STAIRS);
            output.accept(ModBlocks.POLISHED_CALCITE_SLAB);
            output.accept(ModBlocks.POLISHED_CALCITE_WALL);
            output.accept(ModBlocks.CALCITE_BRICKS);
            output.accept(ModBlocks.CALCITE_BRICK_STAIRS);
            output.accept(ModBlocks.CALCITE_BRICK_SLAB);
            output.accept(ModBlocks.CALCITE_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_CALCITE_BRICKS);
            output.accept(ModBlocks.CRACKED_CALCITE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_CALCITE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_CALCITE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_CALCITE_BRICKS);
            output.accept(ModBlocks.MOSSY_CALCITE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_CALCITE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_CALCITE_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_CALCITE_BRICKS);
            output.accept(ModBlocks.CALCITE_BRICK_PILLAR);
            output.accept(ModBlocks.DRIPSTONE_STAIRS);
            output.accept(ModBlocks.DRIPSTONE_SLAB);
            output.accept(ModBlocks.DRIPSTONE_WALL);
            output.accept(ModBlocks.POLISHED_DRIPSTONE);
            output.accept(ModBlocks.POLISHED_DRIPSTONE_STAIRS);
            output.accept(ModBlocks.POLISHED_DRIPSTONE_SLAB);
            output.accept(ModBlocks.POLISHED_DRIPSTONE_WALL);
            output.accept(ModBlocks.DRIPSTONE_BRICKS);
            output.accept(ModBlocks.DRIPSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.DRIPSTONE_BRICK_SLAB);
            output.accept(ModBlocks.DRIPSTONE_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_DRIPSTONE_BRICKS);
            output.accept(ModBlocks.CRACKED_DRIPSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_DRIPSTONE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_DRIPSTONE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_DRIPSTONE_BRICKS);
            output.accept(ModBlocks.MOSSY_DRIPSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_DRIPSTONE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_DRIPSTONE_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_DRIPSTONE_BRICKS);
            output.accept(ModBlocks.DRIPSTONE_BRICK_PILLAR);
            output.accept(ModBlocks.CRACKED_TUFF_BRICKS);
            output.accept(ModBlocks.CRACKED_TUFF_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_TUFF_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_TUFF_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_TUFF_BRICKS);
            output.accept(ModBlocks.MOSSY_TUFF_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_TUFF_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_TUFF_BRICK_WALL);
            output.accept(ModBlocks.POLISHED_ANDESITE_WALL);
            output.accept(ModBlocks.ANDESITE_BRICKS);
            output.accept(ModBlocks.ANDESITE_BRICK_STAIRS);
            output.accept(ModBlocks.ANDESITE_BRICK_SLAB);
            output.accept(ModBlocks.ANDESITE_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_ANDESITE_BRICKS);
            output.accept(ModBlocks.CRACKED_ANDESITE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_ANDESITE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_ANDESITE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_ANDESITE_BRICKS);
            output.accept(ModBlocks.MOSSY_ANDESITE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_ANDESITE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_ANDESITE_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_ANDESITE_BRICKS);
            output.accept(ModBlocks.ANDESITE_BRICK_PILLAR);
            output.accept(ModBlocks.POLISHED_GRANITE_WALL);
            output.accept(ModBlocks.GRANITE_BRICKS);
            output.accept(ModBlocks.GRANITE_BRICK_STAIRS);
            output.accept(ModBlocks.GRANITE_BRICK_SLAB);
            output.accept(ModBlocks.GRANITE_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_GRANITE_BRICKS);
            output.accept(ModBlocks.CRACKED_GRANITE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_GRANITE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_GRANITE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_GRANITE_BRICKS);
            output.accept(ModBlocks.MOSSY_GRANITE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_GRANITE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_GRANITE_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_GRANITE_BRICKS);
            output.accept(ModBlocks.GRANITE_BRICK_PILLAR);
            output.accept(ModBlocks.POLISHED_DIORITE_WALL);
            output.accept(ModBlocks.DIORITE_BRICKS);
            output.accept(ModBlocks.DIORITE_BRICK_STAIRS);
            output.accept(ModBlocks.DIORITE_BRICK_SLAB);
            output.accept(ModBlocks.DIORITE_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_DIORITE_BRICKS);
            output.accept(ModBlocks.CRACKED_DIORITE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_DIORITE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_DIORITE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_DIORITE_BRICKS);
            output.accept(ModBlocks.MOSSY_DIORITE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_DIORITE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_DIORITE_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_DIORITE_BRICKS);
            output.accept(ModBlocks.DIORITE_BRICK_PILLAR);
            output.accept(ModBlocks.QUARTZ_WALL);
            output.accept(ModBlocks.SMOOTH_QUARTZ_WALL);
            output.accept(ModBlocks.QUARTZ_BRICK_STAIRS);
            output.accept(ModBlocks.QUARTZ_BRICK_SLAB);
            output.accept(ModBlocks.QUARTZ_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_QUARTZ_BRICKS);
            output.accept(ModBlocks.CRACKED_QUARTZ_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_QUARTZ_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_QUARTZ_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_QUARTZ_BRICKS);
            output.accept(ModBlocks.MOSSY_QUARTZ_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_QUARTZ_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_QUARTZ_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_BRICKS);
            output.accept(ModBlocks.CRACKED_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_BRICKS);
            output.accept(ModBlocks.MOSSY_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_BRICKS);
            output.accept(ModBlocks.PACKED_MUD_STAIRS);
            output.accept(ModBlocks.PACKED_MUD_SLAB);
            output.accept(ModBlocks.PACKED_MUD_WALL);
            output.accept(ModBlocks.CRACKED_MUD_BRICKS);
            output.accept(ModBlocks.CRACKED_MUD_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_MUD_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_MUD_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_MUD_BRICKS);
            output.accept(ModBlocks.MOSSY_MUD_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_MUD_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_MUD_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_MUD_BRICKS);
            output.accept(ModBlocks.MUD_BRICK_PILLAR);
            output.accept(ModBlocks.SMOOTH_SANDSTONE_WALL);
            output.accept(ModBlocks.CUT_SANDSTONE_STAIRS);
            output.accept(ModBlocks.CUT_SANDSTONE_WALL);
            output.accept(ModBlocks.SANDSTONE_BRICKS);
            output.accept(ModBlocks.SANDSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.SANDSTONE_BRICK_SLAB);
            output.accept(ModBlocks.SANDSTONE_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_SANDSTONE_BRICKS);
            output.accept(ModBlocks.CRACKED_SANDSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_SANDSTONE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_SANDSTONE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_SANDSTONE_BRICKS);
            output.accept(ModBlocks.MOSSY_SANDSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_SANDSTONE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_SANDSTONE_BRICK_WALL);
            output.accept(ModBlocks.SANDSTONE_BRICK_PILLAR);
            output.accept(ModBlocks.SMOOTH_RED_SANDSTONE_WALL);
            output.accept(ModBlocks.CUT_RED_SANDSTONE_STAIRS);
            output.accept(ModBlocks.CUT_RED_SANDSTONE_WALL);
            output.accept(ModBlocks.RED_SANDSTONE_BRICKS);
            output.accept(ModBlocks.RED_SANDSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.RED_SANDSTONE_BRICK_SLAB);
            output.accept(ModBlocks.RED_SANDSTONE_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_RED_SANDSTONE_BRICKS);
            output.accept(ModBlocks.CRACKED_RED_SANDSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_RED_SANDSTONE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_RED_SANDSTONE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_RED_SANDSTONE_BRICKS);
            output.accept(ModBlocks.MOSSY_RED_SANDSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_RED_SANDSTONE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_RED_SANDSTONE_BRICK_WALL);
            output.accept(ModBlocks.RED_SANDSTONE_BRICK_PILLAR);
            output.accept(ModBlocks.END_STONE_STAIRS);
            output.accept(ModBlocks.END_STONE_SLAB);
            output.accept(ModBlocks.END_STONE_WALL);
            output.accept(ModBlocks.POLISHED_END_STONE);
            output.accept(ModBlocks.POLISHED_END_STONE_STAIRS);
            output.accept(ModBlocks.POLISHED_END_STONE_SLAB);
            output.accept(ModBlocks.POLISHED_END_STONE_WALL);
            output.accept(ModBlocks.CRACKED_END_STONE_BRICKS);
            output.accept(ModBlocks.CRACKED_END_STONE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_END_STONE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_END_STONE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_END_STONE_BRICKS);
            output.accept(ModBlocks.MOSSY_END_STONE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_END_STONE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_END_STONE_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_END_STONE_BRICKS);
            output.accept(ModBlocks.END_STONE_BRICK_PILLAR);
            output.accept(ModBlocks.STONE_WALL);
            output.accept(ModBlocks.SMOOTH_STONE_STAIRS);
            output.accept(ModBlocks.SMOOTH_STONE_WALL);
            output.accept(ModBlocks.CRACKED_STONE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_STONE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_STONE_BRICK_WALL);
            output.accept(ModBlocks.STONE_TILES);
            output.accept(ModBlocks.STONE_TILE_STAIRS);
            output.accept(ModBlocks.STONE_TILE_SLAB);
            output.accept(ModBlocks.STONE_TILE_WALL);
            output.accept(ModBlocks.CRACKED_STONE_TILES);
            output.accept(ModBlocks.CRACKED_STONE_TILE_STAIRS);
            output.accept(ModBlocks.CRACKED_STONE_TILE_SLAB);
            output.accept(ModBlocks.CRACKED_STONE_TILE_WALL);
            output.accept(ModBlocks.MOSSY_STONE_TILES);
            output.accept(ModBlocks.MOSSY_STONE_TILE_STAIRS);
            output.accept(ModBlocks.MOSSY_STONE_TILE_SLAB);
            output.accept(ModBlocks.MOSSY_STONE_TILE_WALL);
            output.accept(ModBlocks.STONE_BRICK_PILLAR);
            output.accept(ModBlocks.DEEPSLATE_STAIRS);
            output.accept(ModBlocks.DEEPSLATE_SLAB);
            output.accept(ModBlocks.DEEPSLATE_WALL);
            output.accept(ModBlocks.MOSSY_COBBLED_DEEPSLATE);
            output.accept(ModBlocks.MOSSY_COBBLED_DEEPSLATE_STAIRS);
            output.accept(ModBlocks.MOSSY_COBBLED_DEEPSLATE_SLAB);
            output.accept(ModBlocks.MOSSY_COBBLED_DEEPSLATE_WALL);
            output.accept(ModBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_DEEPSLATE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_DEEPSLATE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_DEEPSLATE_BRICKS);
            output.accept(ModBlocks.MOSSY_DEEPSLATE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_DEEPSLATE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_DEEPSLATE_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_DEEPSLATE_TILE_STAIRS);
            output.accept(ModBlocks.CRACKED_DEEPSLATE_TILE_SLAB);
            output.accept(ModBlocks.CRACKED_DEEPSLATE_TILE_WALL);
            output.accept(ModBlocks.MOSSY_DEEPSLATE_TILES);
            output.accept(ModBlocks.MOSSY_DEEPSLATE_TILE_STAIRS);
            output.accept(ModBlocks.MOSSY_DEEPSLATE_TILE_SLAB);
            output.accept(ModBlocks.MOSSY_DEEPSLATE_TILE_WALL);
            output.accept(ModBlocks.DEEPSLATE_BRICK_PILLAR);
            output.accept(ModBlocks.SCULK_INLAID_DEEPSLATE);
            output.accept(ModBlocks.POLISHED_DEEPSLATE_PRESSURE_PLATE);
            output.accept(ModBlocks.POLISHED_DEEPSLATE_BUTTON);
            output.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_WALL);
            output.accept(ModBlocks.BLACKSTONE_TILES);
            output.accept(ModBlocks.BLACKSTONE_TILE_STAIRS);
            output.accept(ModBlocks.BLACKSTONE_TILE_SLAB);
            output.accept(ModBlocks.BLACKSTONE_TILE_WALL);
            output.accept(ModBlocks.CRACKED_BLACKSTONE_TILES);
            output.accept(ModBlocks.CRACKED_BLACKSTONE_TILE_STAIRS);
            output.accept(ModBlocks.CRACKED_BLACKSTONE_TILE_SLAB);
            output.accept(ModBlocks.CRACKED_BLACKSTONE_TILE_WALL);
            output.accept(ModBlocks.BLACKSTONE_BRICK_PILLAR);
            output.accept(ModBlocks.NETHERRACK_STAIRS);
            output.accept(ModBlocks.NETHERRACK_SLAB);
            output.accept(ModBlocks.NETHERRACK_WALL);
            output.accept(ModBlocks.CRACKED_NETHER_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_NETHER_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_NETHER_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_NETHER_BRICK_FENCE);
            output.accept(ModItems.RED_NETHER_BRICK);
            output.accept(ModBlocks.RED_NETHER_BRICK_FENCE);
            output.accept(ModBlocks.CRACKED_RED_NETHER_BRICKS);
            output.accept(ModBlocks.CRACKED_RED_NETHER_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_RED_NETHER_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_RED_NETHER_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_RED_NETHER_BRICK_FENCE);
            output.accept(ModBlocks.CHISELED_RED_NETHER_BRICKS);
            output.accept(ModItems.BLUE_NETHER_BRICK);
            output.accept(ModBlocks.BLUE_NETHER_BRICKS);
            output.accept(ModBlocks.BLUE_NETHER_BRICK_STAIRS);
            output.accept(ModBlocks.BLUE_NETHER_BRICK_SLAB);
            output.accept(ModBlocks.BLUE_NETHER_BRICK_WALL);
            output.accept(ModBlocks.BLUE_NETHER_BRICK_FENCE);
            output.accept(ModBlocks.CRACKED_BLUE_NETHER_BRICKS);
            output.accept(ModBlocks.CRACKED_BLUE_NETHER_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_BLUE_NETHER_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_BLUE_NETHER_BRICK_WALL);
            output.accept(ModBlocks.CRACKED_BLUE_NETHER_BRICK_FENCE);
            output.accept(ModBlocks.CHISELED_BLUE_NETHER_BRICKS);
            output.accept(ModBlocks.PRISMARINE_BRICK_WALL);
            output.accept(ModBlocks.DARK_PRISMARINE_WALL);
            output.accept(ModBlocks.CRACKED_PRISMARINE_BRICKS);
            output.accept(ModBlocks.CRACKED_PRISMARINE_BRICK_STAIRS);
            output.accept(ModBlocks.CRACKED_PRISMARINE_BRICK_SLAB);
            output.accept(ModBlocks.CRACKED_PRISMARINE_BRICK_WALL);
            output.accept(ModBlocks.MOSSY_PRISMARINE_BRICKS);
            output.accept(ModBlocks.MOSSY_PRISMARINE_BRICK_STAIRS);
            output.accept(ModBlocks.MOSSY_PRISMARINE_BRICK_SLAB);
            output.accept(ModBlocks.MOSSY_PRISMARINE_BRICK_WALL);
            output.accept(ModBlocks.CHISELED_PRISMARINE_BRICKS);
            output.accept(ModBlocks.PRISMARINE_BRICK_PILLAR);
            output.accept(ModBlocks.SNOW_BRICKS);
            output.accept(ModBlocks.SNOW_BRICK_STAIRS);
            output.accept(ModBlocks.SNOW_BRICK_SLAB);
            output.accept(ModBlocks.SNOW_BRICK_WALL);
            output.accept(ModBlocks.SMOOTH_BASALT_STAIRS);
            output.accept(ModBlocks.SMOOTH_BASALT_SLAB);
            output.accept(ModBlocks.SMOOTH_BASALT_WALL);
            output.accept(ModBlocks.PURPUR_WALL);
            output.accept(ModBlocks.CHISELED_PURPUR);
            output.accept(ModBlocks.TINTED_GLASS_PANE);
            if (ModConfigs.enableTerracottaVariants || ModConfigs.configMissing) {
                output.accept(ModBlocks.TERRACOTTA_STAIRS);
                output.accept(ModBlocks.TERRACOTTA_SLAB);
                output.accept(ModBlocks.TERRACOTTA_WALL);
                output.accept(ModBlocks.WHITE_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.WHITE_TERRACOTTA_SLAB);
                output.accept(ModBlocks.WHITE_TERRACOTTA_WALL);
                output.accept(ModBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.LIGHT_GRAY_TERRACOTTA_SLAB);
                output.accept(ModBlocks.LIGHT_GRAY_TERRACOTTA_WALL);
                output.accept(ModBlocks.GRAY_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.GRAY_TERRACOTTA_SLAB);
                output.accept(ModBlocks.GRAY_TERRACOTTA_WALL);
                output.accept(ModBlocks.BLACK_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.BLACK_TERRACOTTA_SLAB);
                output.accept(ModBlocks.BLACK_TERRACOTTA_WALL);
                output.accept(ModBlocks.BROWN_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.BROWN_TERRACOTTA_SLAB);
                output.accept(ModBlocks.BROWN_TERRACOTTA_WALL);
                output.accept(ModBlocks.RED_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.RED_TERRACOTTA_SLAB);
                output.accept(ModBlocks.RED_TERRACOTTA_WALL);
                output.accept(ModBlocks.ORANGE_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.ORANGE_TERRACOTTA_SLAB);
                output.accept(ModBlocks.ORANGE_TERRACOTTA_WALL);
                output.accept(ModBlocks.YELLOW_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.YELLOW_TERRACOTTA_SLAB);
                output.accept(ModBlocks.YELLOW_TERRACOTTA_WALL);
                output.accept(ModBlocks.LIME_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.LIME_TERRACOTTA_SLAB);
                output.accept(ModBlocks.LIME_TERRACOTTA_WALL);
                output.accept(ModBlocks.GREEN_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.GREEN_TERRACOTTA_SLAB);
                output.accept(ModBlocks.GREEN_TERRACOTTA_WALL);
                output.accept(ModBlocks.CYAN_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.CYAN_TERRACOTTA_SLAB);
                output.accept(ModBlocks.CYAN_TERRACOTTA_WALL);
                output.accept(ModBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.LIGHT_BLUE_TERRACOTTA_SLAB);
                output.accept(ModBlocks.LIGHT_BLUE_TERRACOTTA_WALL);
                output.accept(ModBlocks.BLUE_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.BLUE_TERRACOTTA_SLAB);
                output.accept(ModBlocks.BLUE_TERRACOTTA_WALL);
                output.accept(ModBlocks.PURPLE_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.PURPLE_TERRACOTTA_SLAB);
                output.accept(ModBlocks.PURPLE_TERRACOTTA_WALL);
                output.accept(ModBlocks.MAGENTA_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.MAGENTA_TERRACOTTA_SLAB);
                output.accept(ModBlocks.MAGENTA_TERRACOTTA_WALL);
                output.accept(ModBlocks.PINK_TERRACOTTA_STAIRS);
                output.accept(ModBlocks.PINK_TERRACOTTA_SLAB);
                output.accept(ModBlocks.PINK_TERRACOTTA_WALL);
            } else {
                LOGGER.info("Terracotta variants disabled by config (Creative Mode Tab)");
            }
            if (ModConfigs.enableConcreteVariants || ModConfigs.configMissing) {
                output.accept(ModBlocks.WHITE_CONCRETE_STAIRS);
                output.accept(ModBlocks.WHITE_CONCRETE_SLAB);
                output.accept(ModBlocks.WHITE_CONCRETE_WALL);
                output.accept(ModBlocks.LIGHT_GRAY_CONCRETE_STAIRS);
                output.accept(ModBlocks.LIGHT_GRAY_CONCRETE_SLAB);
                output.accept(ModBlocks.LIGHT_GRAY_CONCRETE_WALL);
                output.accept(ModBlocks.GRAY_CONCRETE_STAIRS);
                output.accept(ModBlocks.GRAY_CONCRETE_SLAB);
                output.accept(ModBlocks.GRAY_CONCRETE_WALL);
                output.accept(ModBlocks.BLACK_CONCRETE_STAIRS);
                output.accept(ModBlocks.BLACK_CONCRETE_SLAB);
                output.accept(ModBlocks.BLACK_CONCRETE_WALL);
                output.accept(ModBlocks.BROWN_CONCRETE_STAIRS);
                output.accept(ModBlocks.BROWN_CONCRETE_SLAB);
                output.accept(ModBlocks.BROWN_CONCRETE_WALL);
                output.accept(ModBlocks.RED_CONCRETE_STAIRS);
                output.accept(ModBlocks.RED_CONCRETE_SLAB);
                output.accept(ModBlocks.RED_CONCRETE_WALL);
                output.accept(ModBlocks.ORANGE_CONCRETE_STAIRS);
                output.accept(ModBlocks.ORANGE_CONCRETE_SLAB);
                output.accept(ModBlocks.ORANGE_CONCRETE_WALL);
                output.accept(ModBlocks.YELLOW_CONCRETE_STAIRS);
                output.accept(ModBlocks.YELLOW_CONCRETE_SLAB);
                output.accept(ModBlocks.YELLOW_CONCRETE_WALL);
                output.accept(ModBlocks.LIME_CONCRETE_STAIRS);
                output.accept(ModBlocks.LIME_CONCRETE_SLAB);
                output.accept(ModBlocks.LIME_CONCRETE_WALL);
                output.accept(ModBlocks.GREEN_CONCRETE_STAIRS);
                output.accept(ModBlocks.GREEN_CONCRETE_SLAB);
                output.accept(ModBlocks.GREEN_CONCRETE_WALL);
                output.accept(ModBlocks.CYAN_CONCRETE_STAIRS);
                output.accept(ModBlocks.CYAN_CONCRETE_SLAB);
                output.accept(ModBlocks.CYAN_CONCRETE_WALL);
                output.accept(ModBlocks.LIGHT_BLUE_CONCRETE_STAIRS);
                output.accept(ModBlocks.LIGHT_BLUE_CONCRETE_SLAB);
                output.accept(ModBlocks.LIGHT_BLUE_CONCRETE_WALL);
                output.accept(ModBlocks.BLUE_CONCRETE_STAIRS);
                output.accept(ModBlocks.BLUE_CONCRETE_SLAB);
                output.accept(ModBlocks.BLUE_CONCRETE_WALL);
                output.accept(ModBlocks.PURPLE_CONCRETE_STAIRS);
                output.accept(ModBlocks.PURPLE_CONCRETE_SLAB);
                output.accept(ModBlocks.PURPLE_CONCRETE_WALL);
                output.accept(ModBlocks.MAGENTA_CONCRETE_STAIRS);
                output.accept(ModBlocks.MAGENTA_CONCRETE_SLAB);
                output.accept(ModBlocks.MAGENTA_CONCRETE_WALL);
                output.accept(ModBlocks.PINK_CONCRETE_STAIRS);
                output.accept(ModBlocks.PINK_CONCRETE_SLAB);
                output.accept(ModBlocks.PINK_CONCRETE_WALL);
            } else {
                LOGGER.info("Concrete variants disabled by config (Creative Mode Tab)");
            }

        });
        builder.icon(() -> new ItemStack(ModBlocks.CALCITE_BRICKS.get()));
        builder.title(Component.translatable(CINCHSMISSINGBLOCKS_TAB_TITLE));
        return builder.build();
    });
}