package net.cinchtail.cinchsmissingblocks.datagen;

import net.cinchtail.cinchsmissingblocks.block.ModBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootSubProvider;
import net.minecraft.core.HolderLookup;


import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootSubProvider {
    public ModLootTableProvider(FabricPackOutput packOutput, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(packOutput, registriesFuture);
    }

    @Override
    public void generate() {

        dropSelf(ModBlocks.CALCITE_STAIRS);
        add(ModBlocks.CALCITE_WALL, createSlabItemTable(ModBlocks.CALCITE_SLAB));
        dropSelf(ModBlocks.CALCITE_WALL);
        dropSelf(ModBlocks.POLISHED_CALCITE);
        dropSelf(ModBlocks.POLISHED_CALCITE_STAIRS);
        add(ModBlocks.POLISHED_CALCITE_SLAB, createSlabItemTable(ModBlocks.POLISHED_CALCITE_SLAB));
        dropSelf(ModBlocks.POLISHED_CALCITE_WALL);
        dropSelf(ModBlocks.CALCITE_BRICKS);
        dropSelf(ModBlocks.CALCITE_BRICK_STAIRS);
        add(ModBlocks.CALCITE_BRICK_SLAB, createSlabItemTable(ModBlocks.CALCITE_BRICK_SLAB));
        dropSelf(ModBlocks.CALCITE_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_CALCITE_BRICKS);
        dropSelf(ModBlocks.CRACKED_CALCITE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_CALCITE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_CALCITE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_CALCITE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_CALCITE_BRICKS);
        dropSelf(ModBlocks.MOSSY_CALCITE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_CALCITE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_CALCITE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_CALCITE_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_CALCITE_BRICKS);
        dropSelf(ModBlocks.CALCITE_BRICK_PILLAR);

        dropSelf(ModBlocks.DRIPSTONE_STAIRS);
        add(ModBlocks.DRIPSTONE_WALL, createSlabItemTable(ModBlocks.DRIPSTONE_SLAB));
        dropSelf(ModBlocks.DRIPSTONE_WALL);
        dropSelf(ModBlocks.POLISHED_DRIPSTONE);
        dropSelf(ModBlocks.POLISHED_DRIPSTONE_STAIRS);
        add(ModBlocks.POLISHED_DRIPSTONE_SLAB, createSlabItemTable(ModBlocks.POLISHED_DRIPSTONE_SLAB));
        dropSelf(ModBlocks.POLISHED_DRIPSTONE_WALL);
        dropSelf(ModBlocks.DRIPSTONE_BRICKS);
        dropSelf(ModBlocks.DRIPSTONE_BRICK_STAIRS);
        add(ModBlocks.DRIPSTONE_BRICK_SLAB, createSlabItemTable(ModBlocks.DRIPSTONE_BRICK_SLAB));
        dropSelf(ModBlocks.DRIPSTONE_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_DRIPSTONE_BRICKS);
        dropSelf(ModBlocks.CRACKED_DRIPSTONE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_DRIPSTONE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_DRIPSTONE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_DRIPSTONE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_DRIPSTONE_BRICKS);
        dropSelf(ModBlocks.MOSSY_DRIPSTONE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_DRIPSTONE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_DRIPSTONE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_DRIPSTONE_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_DRIPSTONE_BRICKS);
        dropSelf(ModBlocks.DRIPSTONE_BRICK_PILLAR);

        dropSelf(ModBlocks.CRACKED_TUFF_BRICKS);
        dropSelf(ModBlocks.CRACKED_TUFF_BRICK_STAIRS);
        add(ModBlocks.CRACKED_TUFF_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_TUFF_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_TUFF_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_TUFF_BRICKS);
        dropSelf(ModBlocks.MOSSY_TUFF_BRICK_STAIRS);
        add(ModBlocks.MOSSY_TUFF_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_TUFF_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_TUFF_BRICK_WALL);

        dropSelf(ModBlocks.POLISHED_ANDESITE_WALL);
        dropSelf(ModBlocks.ANDESITE_BRICKS);
        dropSelf(ModBlocks.ANDESITE_BRICK_STAIRS);
        add(ModBlocks.ANDESITE_BRICK_SLAB, createSlabItemTable(ModBlocks.ANDESITE_BRICK_SLAB));
        dropSelf(ModBlocks.ANDESITE_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_ANDESITE_BRICKS);
        dropSelf(ModBlocks.CRACKED_ANDESITE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_ANDESITE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_ANDESITE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_ANDESITE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_ANDESITE_BRICKS);
        dropSelf(ModBlocks.MOSSY_ANDESITE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_ANDESITE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_ANDESITE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_ANDESITE_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_ANDESITE_BRICKS);
        dropSelf(ModBlocks.ANDESITE_BRICK_PILLAR);

        dropSelf(ModBlocks.POLISHED_GRANITE_WALL);
        dropSelf(ModBlocks.GRANITE_BRICKS);
        dropSelf(ModBlocks.GRANITE_BRICK_STAIRS);
        add(ModBlocks.GRANITE_BRICK_SLAB, createSlabItemTable(ModBlocks.GRANITE_BRICK_SLAB));
        dropSelf(ModBlocks.GRANITE_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_GRANITE_BRICKS);
        dropSelf(ModBlocks.CRACKED_GRANITE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_GRANITE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_GRANITE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_GRANITE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_GRANITE_BRICKS);
        dropSelf(ModBlocks.MOSSY_GRANITE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_GRANITE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_GRANITE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_GRANITE_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_GRANITE_BRICKS);
        dropSelf(ModBlocks.GRANITE_BRICK_PILLAR);

        dropSelf(ModBlocks.POLISHED_DIORITE_WALL);
        dropSelf(ModBlocks.DIORITE_BRICKS);
        dropSelf(ModBlocks.DIORITE_BRICK_STAIRS);
        add(ModBlocks.DIORITE_BRICK_SLAB, createSlabItemTable(ModBlocks.DIORITE_BRICK_SLAB));
        dropSelf(ModBlocks.DIORITE_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_DIORITE_BRICKS);
        dropSelf(ModBlocks.CRACKED_DIORITE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_DIORITE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_DIORITE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_DIORITE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_DIORITE_BRICKS);
        dropSelf(ModBlocks.MOSSY_DIORITE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_DIORITE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_DIORITE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_DIORITE_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_DIORITE_BRICKS);
        dropSelf(ModBlocks.DIORITE_BRICK_PILLAR);

        dropSelf(ModBlocks.QUARTZ_WALL);
        dropSelf(ModBlocks.SMOOTH_QUARTZ_WALL);
        dropSelf(ModBlocks.QUARTZ_BRICK_STAIRS);
        add(ModBlocks.QUARTZ_BRICK_SLAB, createSlabItemTable(ModBlocks.QUARTZ_BRICK_SLAB));
        dropSelf(ModBlocks.QUARTZ_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_QUARTZ_BRICKS);
        dropSelf(ModBlocks.CRACKED_QUARTZ_BRICK_STAIRS);
        add(ModBlocks.CRACKED_QUARTZ_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_QUARTZ_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_QUARTZ_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_QUARTZ_BRICKS);
        dropSelf(ModBlocks.MOSSY_QUARTZ_BRICK_STAIRS);
        add(ModBlocks.MOSSY_QUARTZ_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_QUARTZ_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_QUARTZ_BRICK_WALL);

        dropSelf(ModBlocks.CRACKED_BRICKS);
        dropSelf(ModBlocks.CRACKED_BRICK_STAIRS);
        add(ModBlocks.CRACKED_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_BRICKS);
        dropSelf(ModBlocks.MOSSY_BRICK_STAIRS);
        add(ModBlocks.MOSSY_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_BRICKS);

        dropSelf(ModBlocks.PACKED_MUD_STAIRS);
        add(ModBlocks.PACKED_MUD_SLAB, createSlabItemTable(ModBlocks.PACKED_MUD_SLAB));
        dropSelf(ModBlocks.PACKED_MUD_WALL);
        dropSelf(ModBlocks.CRACKED_MUD_BRICKS);
        dropSelf(ModBlocks.CRACKED_MUD_BRICK_STAIRS);
        add(ModBlocks.CRACKED_MUD_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_MUD_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_MUD_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_MUD_BRICKS);
        dropSelf(ModBlocks.MOSSY_MUD_BRICK_STAIRS);
        add(ModBlocks.MOSSY_MUD_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_MUD_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_MUD_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_MUD_BRICKS);
        dropSelf(ModBlocks.MUD_BRICK_PILLAR);

        dropSelf(ModBlocks.CRACKED_RESIN_BRICKS);
        dropSelf(ModBlocks.CRACKED_RESIN_BRICK_STAIRS);
        add(ModBlocks.CRACKED_RESIN_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_RESIN_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_RESIN_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_RESIN_BRICKS);
        dropSelf(ModBlocks.MOSSY_RESIN_BRICK_STAIRS);
        add(ModBlocks.MOSSY_RESIN_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_RESIN_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_RESIN_BRICK_WALL);

        dropSelf(ModBlocks.SMOOTH_SANDSTONE_WALL);
        dropSelf(ModBlocks.CUT_SANDSTONE_STAIRS);
        dropSelf(ModBlocks.CUT_SANDSTONE_WALL);
        dropSelf(ModBlocks.CRACKED_SANDSTONE_BRICKS);
        dropSelf(ModBlocks.CRACKED_SANDSTONE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_SANDSTONE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_SANDSTONE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_SANDSTONE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_SANDSTONE_BRICKS);
        dropSelf(ModBlocks.MOSSY_SANDSTONE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_SANDSTONE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_SANDSTONE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_SANDSTONE_BRICK_WALL);

        dropSelf(ModBlocks.SMOOTH_RED_SANDSTONE_WALL);
        dropSelf(ModBlocks.CUT_RED_SANDSTONE_STAIRS);
        dropSelf(ModBlocks.CUT_RED_SANDSTONE_WALL);
        dropSelf(ModBlocks.CRACKED_RED_SANDSTONE_BRICKS);
        dropSelf(ModBlocks.CRACKED_RED_SANDSTONE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_RED_SANDSTONE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_RED_SANDSTONE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_RED_SANDSTONE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_RED_SANDSTONE_BRICKS);
        dropSelf(ModBlocks.MOSSY_RED_SANDSTONE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_RED_SANDSTONE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_RED_SANDSTONE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_RED_SANDSTONE_BRICK_WALL);

        dropSelf(ModBlocks.END_STONE_STAIRS);
        add(ModBlocks.END_STONE_WALL, createSlabItemTable(ModBlocks.END_STONE_SLAB));
        dropSelf(ModBlocks.END_STONE_WALL);
        dropSelf(ModBlocks.POLISHED_END_STONE);
        dropSelf(ModBlocks.POLISHED_END_STONE_STAIRS);
        add(ModBlocks.POLISHED_END_STONE_SLAB, createSlabItemTable(ModBlocks.POLISHED_END_STONE_SLAB));
        dropSelf(ModBlocks.POLISHED_END_STONE_WALL);
        dropSelf(ModBlocks.CRACKED_END_STONE_BRICKS);
        dropSelf(ModBlocks.CRACKED_END_STONE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_END_STONE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_END_STONE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_END_STONE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_END_STONE_BRICKS);
        dropSelf(ModBlocks.MOSSY_END_STONE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_END_STONE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_END_STONE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_END_STONE_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_END_STONE_BRICKS);
        dropSelf(ModBlocks.END_STONE_BRICK_PILLAR);

        dropSelf(ModBlocks.STONE_WALL);
        dropSelf(ModBlocks.SMOOTH_STONE_STAIRS);
        dropSelf(ModBlocks.SMOOTH_STONE_WALL);
        dropSelf(ModBlocks.CRACKED_STONE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_STONE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_STONE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_STONE_BRICK_WALL);
        dropSelf(ModBlocks.STONE_TILES);
        dropSelf(ModBlocks.STONE_TILE_STAIRS);
        add(ModBlocks.STONE_TILE_SLAB, createSlabItemTable(ModBlocks.STONE_TILE_SLAB));
        dropSelf(ModBlocks.STONE_TILE_WALL);
        dropSelf(ModBlocks.CRACKED_STONE_TILES);
        dropSelf(ModBlocks.CRACKED_STONE_TILE_STAIRS);
        add(ModBlocks.CRACKED_STONE_TILE_SLAB, createSlabItemTable(ModBlocks.CRACKED_STONE_TILE_SLAB));
        dropSelf(ModBlocks.CRACKED_STONE_TILE_WALL);
        dropSelf(ModBlocks.MOSSY_STONE_TILES);
        dropSelf(ModBlocks.MOSSY_STONE_TILE_STAIRS);
        add(ModBlocks.MOSSY_STONE_TILE_SLAB, createSlabItemTable(ModBlocks.MOSSY_STONE_TILE_SLAB));
        dropSelf(ModBlocks.MOSSY_STONE_TILE_WALL);
        dropSelf(ModBlocks.STONE_BRICK_PILLAR);

        dropSelf(ModBlocks.DEEPSLATE_STAIRS);
        add(ModBlocks.DEEPSLATE_SLAB, createSlabItemTable(ModBlocks.DEEPSLATE_SLAB));
        dropSelf(ModBlocks.DEEPSLATE_WALL);
        dropSelf(ModBlocks.MOSSY_COBBLED_DEEPSLATE);
        dropSelf(ModBlocks.MOSSY_COBBLED_DEEPSLATE_STAIRS);
        add(ModBlocks.MOSSY_COBBLED_DEEPSLATE_SLAB, createSlabItemTable(ModBlocks.MOSSY_COBBLED_DEEPSLATE_SLAB));
        dropSelf(ModBlocks.MOSSY_COBBLED_DEEPSLATE_WALL);
        dropSelf(ModBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_DEEPSLATE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_DEEPSLATE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_DEEPSLATE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_DEEPSLATE_BRICKS);
        dropSelf(ModBlocks.MOSSY_DEEPSLATE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_DEEPSLATE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_DEEPSLATE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_DEEPSLATE_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_DEEPSLATE_TILE_STAIRS);
        add(ModBlocks.CRACKED_DEEPSLATE_TILE_SLAB, createSlabItemTable(ModBlocks.CRACKED_DEEPSLATE_TILE_SLAB));
        dropSelf(ModBlocks.CRACKED_DEEPSLATE_TILE_WALL);
        dropSelf(ModBlocks.MOSSY_DEEPSLATE_TILES);
        dropSelf(ModBlocks.MOSSY_DEEPSLATE_TILE_STAIRS);
        add(ModBlocks.MOSSY_DEEPSLATE_TILE_SLAB, createSlabItemTable(ModBlocks.MOSSY_DEEPSLATE_TILE_SLAB));
        dropSelf(ModBlocks.MOSSY_DEEPSLATE_TILE_WALL);
        dropSelf(ModBlocks.DEEPSLATE_BRICK_PILLAR);
        dropWhenSilkTouch(ModBlocks.SCULK_INLAID_DEEPSLATE);
        dropSelf(ModBlocks.POLISHED_DEEPSLATE_PRESSURE_PLATE);
        dropSelf(ModBlocks.POLISHED_DEEPSLATE_BUTTON);

        dropSelf(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_WALL);
        dropSelf(ModBlocks.BLACKSTONE_TILES);
        dropSelf(ModBlocks.BLACKSTONE_TILE_STAIRS);
        add(ModBlocks.BLACKSTONE_TILE_SLAB, createSlabItemTable(ModBlocks.BLACKSTONE_TILE_SLAB));
        dropSelf(ModBlocks.BLACKSTONE_TILE_WALL);
        dropSelf(ModBlocks.CRACKED_BLACKSTONE_TILES);
        dropSelf(ModBlocks.CRACKED_BLACKSTONE_TILE_STAIRS);
        add(ModBlocks.CRACKED_BLACKSTONE_TILE_SLAB, createSlabItemTable(ModBlocks.CRACKED_BLACKSTONE_TILE_SLAB));
        dropSelf(ModBlocks.CRACKED_BLACKSTONE_TILE_WALL);
        dropSelf(ModBlocks.BLACKSTONE_BRICK_PILLAR);

        dropSelf(ModBlocks.NETHERRACK_STAIRS);
        add(ModBlocks.NETHERRACK_SLAB, createSlabItemTable(ModBlocks.NETHERRACK_SLAB));
        dropSelf(ModBlocks.NETHERRACK_WALL);

        dropSelf(ModBlocks.CRACKED_NETHER_BRICK_STAIRS);
        add(ModBlocks.CRACKED_NETHER_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_NETHER_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_NETHER_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_NETHER_BRICK_FENCE);

        dropSelf(ModBlocks.RED_NETHER_BRICK_FENCE);
        dropSelf(ModBlocks.CRACKED_RED_NETHER_BRICKS);
        dropSelf(ModBlocks.CRACKED_RED_NETHER_BRICK_STAIRS);
        add(ModBlocks.CRACKED_RED_NETHER_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_RED_NETHER_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_RED_NETHER_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_RED_NETHER_BRICK_FENCE);
        dropSelf(ModBlocks.CHISELED_RED_NETHER_BRICKS);

        dropSelf(ModBlocks.BLUE_NETHER_BRICKS);
        dropSelf(ModBlocks.BLUE_NETHER_BRICK_STAIRS);
        add(ModBlocks.BLUE_NETHER_BRICK_SLAB, createSlabItemTable(ModBlocks.BLUE_NETHER_BRICK_SLAB));
        dropSelf(ModBlocks.BLUE_NETHER_BRICK_WALL);
        dropSelf(ModBlocks.BLUE_NETHER_BRICK_FENCE);
        dropSelf(ModBlocks.CRACKED_BLUE_NETHER_BRICKS);
        dropSelf(ModBlocks.CRACKED_BLUE_NETHER_BRICK_STAIRS);
        add(ModBlocks.CRACKED_BLUE_NETHER_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_BLUE_NETHER_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_BLUE_NETHER_BRICK_WALL);
        dropSelf(ModBlocks.CRACKED_BLUE_NETHER_BRICK_FENCE);
        dropSelf(ModBlocks.CHISELED_BLUE_NETHER_BRICKS);

        dropSelf(ModBlocks.PRISMARINE_BRICK_WALL);
        dropSelf(ModBlocks.DARK_PRISMARINE_WALL);
        dropSelf(ModBlocks.CRACKED_PRISMARINE_BRICKS);
        dropSelf(ModBlocks.CRACKED_PRISMARINE_BRICK_STAIRS);
        add(ModBlocks.CRACKED_PRISMARINE_BRICK_SLAB, createSlabItemTable(ModBlocks.CRACKED_PRISMARINE_BRICK_SLAB));
        dropSelf(ModBlocks.CRACKED_PRISMARINE_BRICK_WALL);
        dropSelf(ModBlocks.MOSSY_PRISMARINE_BRICKS);
        dropSelf(ModBlocks.MOSSY_PRISMARINE_BRICK_STAIRS);
        add(ModBlocks.MOSSY_PRISMARINE_BRICK_SLAB, createSlabItemTable(ModBlocks.MOSSY_PRISMARINE_BRICK_SLAB));
        dropSelf(ModBlocks.MOSSY_PRISMARINE_BRICK_WALL);
        dropSelf(ModBlocks.CHISELED_PRISMARINE_BRICKS);
        dropSelf(ModBlocks.PRISMARINE_BRICK_PILLAR);

        dropSelf(ModBlocks.SMOOTH_BASALT_STAIRS);
        add(ModBlocks.SMOOTH_BASALT_SLAB, createSlabItemTable(ModBlocks.SMOOTH_BASALT_SLAB));
        dropSelf(ModBlocks.SMOOTH_BASALT_WALL);

        dropSelf(ModBlocks.PURPUR_WALL);
        dropSelf(ModBlocks.CHISELED_PURPUR);

        dropWhenSilkTouch(ModBlocks.TINTED_GLASS_PANE);

        dropSelf(ModBlocks.TERRACOTTA_STAIRS);
        add(ModBlocks.TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.TERRACOTTA_SLAB));
        dropSelf(ModBlocks.TERRACOTTA_WALL);
        dropSelf(ModBlocks.WHITE_TERRACOTTA_STAIRS);
        add(ModBlocks.WHITE_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.WHITE_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.WHITE_TERRACOTTA_WALL);
        dropSelf(ModBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS);
        add(ModBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.LIGHT_GRAY_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.LIGHT_GRAY_TERRACOTTA_WALL);
        dropSelf(ModBlocks.GRAY_TERRACOTTA_STAIRS);
        add(ModBlocks.GRAY_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.GRAY_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.GRAY_TERRACOTTA_WALL);
        dropSelf(ModBlocks.BLACK_TERRACOTTA_STAIRS);
        add(ModBlocks.BLACK_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.BLACK_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.BLACK_TERRACOTTA_WALL);
        dropSelf(ModBlocks.BROWN_TERRACOTTA_STAIRS);
        add(ModBlocks.BROWN_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.BROWN_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.BROWN_TERRACOTTA_WALL);
        dropSelf(ModBlocks.RED_TERRACOTTA_STAIRS);
        add(ModBlocks.RED_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.RED_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.RED_TERRACOTTA_WALL);
        dropSelf(ModBlocks.ORANGE_TERRACOTTA_STAIRS);
        add(ModBlocks.ORANGE_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.ORANGE_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.ORANGE_TERRACOTTA_WALL);
        dropSelf(ModBlocks.YELLOW_TERRACOTTA_STAIRS);
        add(ModBlocks.YELLOW_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.YELLOW_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.YELLOW_TERRACOTTA_WALL);
        dropSelf(ModBlocks.LIME_TERRACOTTA_STAIRS);
        add(ModBlocks.LIME_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.LIME_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.LIME_TERRACOTTA_WALL);
        dropSelf(ModBlocks.GREEN_TERRACOTTA_STAIRS);
        add(ModBlocks.GREEN_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.GREEN_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.GREEN_TERRACOTTA_WALL);
        dropSelf(ModBlocks.CYAN_TERRACOTTA_STAIRS);
        add(ModBlocks.CYAN_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.CYAN_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.CYAN_TERRACOTTA_WALL);
        dropSelf(ModBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS);
        add(ModBlocks.LIGHT_BLUE_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.LIGHT_BLUE_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.LIGHT_BLUE_TERRACOTTA_WALL);
        dropSelf(ModBlocks.BLUE_TERRACOTTA_STAIRS);
        add(ModBlocks.BLUE_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.BLUE_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.BLUE_TERRACOTTA_WALL);
        dropSelf(ModBlocks.PURPLE_TERRACOTTA_STAIRS);
        add(ModBlocks.PURPLE_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.PURPLE_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.PURPLE_TERRACOTTA_WALL);
        dropSelf(ModBlocks.MAGENTA_TERRACOTTA_STAIRS);
        add(ModBlocks.MAGENTA_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.MAGENTA_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.MAGENTA_TERRACOTTA_WALL);
        dropSelf(ModBlocks.PINK_TERRACOTTA_STAIRS);
        add(ModBlocks.PINK_TERRACOTTA_SLAB, createSlabItemTable(ModBlocks.PINK_TERRACOTTA_SLAB));
        dropSelf(ModBlocks.PINK_TERRACOTTA_WALL);

        dropSelf(ModBlocks.WHITE_CONCRETE_STAIRS);
        add(ModBlocks.WHITE_CONCRETE_SLAB, createSlabItemTable(ModBlocks.WHITE_CONCRETE_SLAB));
        dropSelf(ModBlocks.WHITE_CONCRETE_WALL);
        dropSelf(ModBlocks.LIGHT_GRAY_CONCRETE_STAIRS);
        add(ModBlocks.LIGHT_GRAY_CONCRETE_SLAB, createSlabItemTable(ModBlocks.LIGHT_GRAY_CONCRETE_SLAB));
        dropSelf(ModBlocks.LIGHT_GRAY_CONCRETE_WALL);
        dropSelf(ModBlocks.GRAY_CONCRETE_STAIRS);
        add(ModBlocks.GRAY_CONCRETE_SLAB, createSlabItemTable(ModBlocks.GRAY_CONCRETE_SLAB));
        dropSelf(ModBlocks.GRAY_CONCRETE_WALL);
        dropSelf(ModBlocks.BLACK_CONCRETE_STAIRS);
        add(ModBlocks.BLACK_CONCRETE_SLAB, createSlabItemTable(ModBlocks.BLACK_CONCRETE_SLAB));
        dropSelf(ModBlocks.BLACK_CONCRETE_WALL);
        dropSelf(ModBlocks.BROWN_CONCRETE_STAIRS);
        add(ModBlocks.BROWN_CONCRETE_SLAB, createSlabItemTable(ModBlocks.BROWN_CONCRETE_SLAB));
        dropSelf(ModBlocks.BROWN_CONCRETE_WALL);
        dropSelf(ModBlocks.RED_CONCRETE_STAIRS);
        add(ModBlocks.RED_CONCRETE_SLAB, createSlabItemTable(ModBlocks.RED_CONCRETE_SLAB));
        dropSelf(ModBlocks.RED_CONCRETE_WALL);
        dropSelf(ModBlocks.ORANGE_CONCRETE_STAIRS);
        add(ModBlocks.ORANGE_CONCRETE_SLAB, createSlabItemTable(ModBlocks.ORANGE_CONCRETE_SLAB));
        dropSelf(ModBlocks.ORANGE_CONCRETE_WALL);
        dropSelf(ModBlocks.YELLOW_CONCRETE_STAIRS);
        add(ModBlocks.YELLOW_CONCRETE_SLAB, createSlabItemTable(ModBlocks.YELLOW_CONCRETE_SLAB));
        dropSelf(ModBlocks.YELLOW_CONCRETE_WALL);
        dropSelf(ModBlocks.LIME_CONCRETE_STAIRS);
        add(ModBlocks.LIME_CONCRETE_SLAB, createSlabItemTable(ModBlocks.LIME_CONCRETE_SLAB));
        dropSelf(ModBlocks.LIME_CONCRETE_WALL);
        dropSelf(ModBlocks.GREEN_CONCRETE_STAIRS);
        add(ModBlocks.GREEN_CONCRETE_SLAB, createSlabItemTable(ModBlocks.GREEN_CONCRETE_SLAB));
        dropSelf(ModBlocks.GREEN_CONCRETE_WALL);
        dropSelf(ModBlocks.CYAN_CONCRETE_STAIRS);
        add(ModBlocks.CYAN_CONCRETE_SLAB, createSlabItemTable(ModBlocks.CYAN_CONCRETE_SLAB));
        dropSelf(ModBlocks.CYAN_CONCRETE_WALL);
        dropSelf(ModBlocks.LIGHT_BLUE_CONCRETE_STAIRS);
        add(ModBlocks.LIGHT_BLUE_CONCRETE_SLAB, createSlabItemTable(ModBlocks.LIGHT_BLUE_CONCRETE_SLAB));
        dropSelf(ModBlocks.LIGHT_BLUE_CONCRETE_WALL);
        dropSelf(ModBlocks.BLUE_CONCRETE_STAIRS);
        add(ModBlocks.BLUE_CONCRETE_SLAB, createSlabItemTable(ModBlocks.BLUE_CONCRETE_SLAB));
        dropSelf(ModBlocks.BLUE_CONCRETE_WALL);
        dropSelf(ModBlocks.PURPLE_CONCRETE_STAIRS);
        add(ModBlocks.PURPLE_CONCRETE_SLAB, createSlabItemTable(ModBlocks.PURPLE_CONCRETE_SLAB));
        dropSelf(ModBlocks.PURPLE_CONCRETE_WALL);
        dropSelf(ModBlocks.MAGENTA_CONCRETE_STAIRS);
        add(ModBlocks.MAGENTA_CONCRETE_SLAB, createSlabItemTable(ModBlocks.MAGENTA_CONCRETE_SLAB));
        dropSelf(ModBlocks.MAGENTA_CONCRETE_WALL);
        dropSelf(ModBlocks.PINK_CONCRETE_STAIRS);
        add(ModBlocks.PINK_CONCRETE_SLAB, createSlabItemTable(ModBlocks.PINK_CONCRETE_SLAB));
        dropSelf(ModBlocks.PINK_CONCRETE_WALL);
    }
}